### PR TITLE
Initial German translation

### PR DESCRIPTION
**Pull request by Herbert-Karl**
Created a german translation.
It is a base to be worked on.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
We don't take translations via pull request. You should try to contact the German translation maintainer; or if he's unavailable or something , contact @Ivanovic to see if you can take over as German translation maintainer.

**Comment by CelticMinstrel** [comment]
I just noticed that this is steam-meta so it's possible that there are different guidelines, so I'd wait for someone else to confirm if what I said is correct.

**Comment by hrubymar10** [comment]
@shikadiqueen took it under her wings so @Herbert-Karl is right with this PR.

@shikadiqueen , you should add `CONTRIBUTING.md` with instructions.

@Herbert-Karl , you may not know from Discord, but @shikadiqueen recommended to wait with translations, because Steam description is not final yet.

**Comment by Herbert-Karl** [comment]
@hrubymar10  no, i dont use Discord. Thanks for letting me know.

**Comment by aquileia** [comment]
As to the translation itself, there's a few errors yet, I'd suggest
-  mit ~~mit~~ Fantasy-Elementen
- der vielen Abenteuer --> ihrer zahlreichen Abenteuer
- Begebe --> Begib
- Nekromanten --> Totenbeschwörer (to match the unit name)
- das Böse selbst --> ein dort lauerndes Übel (?, neither are quite right)

**Comment by Herbert-Karl** [comment]
@aquileia  thx for the Feedback. I updated the translation.

**Comment by irydacea** [comment]
I'll add a `CONTRIBUTING.md` as soon as there's definitive content for the intro and description sections. I guess I should bug @Vultraz to get those finished ASAP.

I actually haven't decided whether to use pull requests or issues with attachment. My original plan was to use the latter, but if I use PRs I guess I can squash them and `msgmerge` them locally before pushing upstream.

**Comment by Herbert-Karl** [comment]
closing this because of the contributing.md stating that only established translators are accepted

**Pull request closed without merging**
